/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const customermessage_Logic_PreprocessMessages = require('./code/customermessage-logic-preprocessMessages');
const productfaq_Logic_EmbedFAQ = require('./code/productfaq-logic-embedFAQ');

class okta_adi_03_stundentf_03Srv extends LCAPApplicationService {
    async init() {

        this.before('READ', 'CustomerMessage', async (request) => {
            await customermessage_Logic_PreprocessMessages(request);
        });

        this.after(['CREATE', 'UPDATE'], 'ProductFAQ', async (results, request) => {
            await productfaq_Logic_EmbedFAQ(results, request);
        });

        return super.init();
    }
}


module.exports = {
    okta_adi_03_stundentf_03Srv
};